# Operations: +,-,*,/,//,**,% 
a = int(input("Enter a number: "))
b = int(input("Enter a number: "))
print("Sum:",a+b)
print("Difference:",a-b)
print("Product:",a*b)
print("Quotient:",a/b)
print("Integer part of Quotient:",a//b)
print("Power:",a**b)
print("Remainder:",a%b)